language: ruby
rvm:
  - 2.2.3

gemfile:
  - Gemfile
after_success:
- gem install bundler
- chmod ugo+x ./after_deploy.rb
- ruby ./after_deploy.rb
#comment to test
deploy:
- provider: elasticbeanstalk
- access_key_id: "AKIAIGCLPOYPKGXSOKMA"
- secret_access_key: "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"
- region: us-west-2
- app: rubyonrails
- env: rails-env-dev
- bucket_name: elasticbeanstalk-us-west-2-901766598996
